{{- range .Values.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongo-collections-controller
  namespace: {{ . }}
  labels:
    app.kubernetes.io/component: mongo-collections-controller
    app.kubernetes.io/name: mongo-collections-controller
rules:
  - apiGroups:
      - pincette.net
    resources:
      - mongocollections
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pincette.net
    resources:
      - mongocollections/status
    verbs:
      - patch
      - update
{{- end }}
