{{- $namespace := .Release.Namespace -}}
{{- range .Values.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo-collections-controller
  namespace: {{ . }}
  labels:
    app.kubernetes.io/component: mongo-collections-controller
    app.kubernetes.io/name: mongo-collections-controller
subjects:
  - kind: ServiceAccount
    name: mongo-collections-controller
    namespace: {{ $namespace }}
roleRef:
  name: mongo-collections-controller
  apiGroup: rbac.authorization.k8s.io
  kind: Role
{{- end }}
