---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-collections-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: mongo-collections-controller
    app.kubernetes.io/name: mongo-collections-controller
