---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mongocollections.pincette.net
spec:
  group: pincette.net
  names:
    kind: MongoCollection
    plural: mongocollections
    singular: mongocollection
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.health.status
          name: Health
          type: string
        - jsonPath: .status.phase
          name: Phase
          type: string
        - jsonPath: .status.status
          name: Health
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                capped:
                  type: boolean
                changeStreamPreAndPostImages:
                  type: boolean
                clustered:
                  type: boolean
                collation:
                  properties:
                    alternate:
                      type: string
                    backwards:
                      type: boolean
                    caseFirst:
                      type: string
                    caseLevel:
                      type: boolean
                    locale:
                      type: string
                    maxVariable:
                      type: string
                    normalization:
                      type: boolean
                    numericOrdering:
                      type: boolean
                    strength:
                      type: integer
                  required:
                    - locale
                  type: object
                encryptedFields:
                  properties:
                    fields:
                      items:
                        properties:
                          bsonType:
                            type: string
                          keyId:
                            type: string
                          path:
                            type: string
                          queries:
                            items:
                              additionalProperties:
                                enum:
                                  - equality
                                  - none
                                type: string
                              type: object
                            type: array
                        required:
                          - bsonType
                          - keyId
                          - path
                        type: object
                      type: array
                    queryPatterns:
                      items:
                        additionalProperties:
                          enum:
                            - equality
                            - none
                          type: string
                        type: object
                      type: array
                  type: object
                expireAfterSeconds:
                  type: integer
                indexes:
                  items:
                    properties:
                      keys:
                        items:
                          properties:
                            direction:
                              type: integer
                            field:
                              type: string
                          required:
                            - direction
                            - field
                          type: object
                        type: array
                      options:
                        properties:
                          bits:
                            type: integer
                          collation:
                            properties:
                              alternate:
                                type: string
                              backwards:
                                type: boolean
                              caseFirst:
                                type: string
                              caseLevel:
                                type: boolean
                              locale:
                                type: string
                              maxVariable:
                                type: string
                              normalization:
                                type: boolean
                              numericOrdering:
                                type: boolean
                              strength:
                                type: integer
                            required:
                              - locale
                            type: object
                          defaultLanguage:
                            type: string
                          expireAfterSeconds:
                            type: integer
                          hidden:
                            type: boolean
                          languageOverride:
                            type: string
                          max:
                            type: number
                          min:
                            type: number
                          name:
                            type: string
                          partialFilterExpression:
                            additionalProperties:
                              type: object
                            type: object
                          sparse:
                            type: boolean
                          sphereIndexVersion:
                            type: integer
                          textIndexVersion:
                            type: integer
                          unique:
                            type: boolean
                          weights:
                            additionalProperties:
                              type: integer
                            type: object
                          wildcardProjection:
                            additionalProperties:
                              type: integer
                            type: object
                        type: object
                    required:
                      - keys
                    type: object
                  type: array
                max:
                  type: integer
                name:
                  type: string
                size:
                  type: integer
                timeSeries:
                  properties:
                    granularity:
                      enum:
                        - hours
                        - minutes
                        - seconds
                      type: string
                    metaField:
                      type: string
                    timeField:
                      type: string
                  required:
                    - timeField
                  type: object
                validator:
                  additionalProperties:
                    type: object
                  type: object
                validationAction:
                  enum:
                    - error
                    - warn
                  type: string
                validationLevel:
                  enum:
                    - moderate
                    - "off"
                    - strict
                  type: string
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        type: string
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    type: object
                  type: array
                health:
                  properties:
                    status:
                      type: string
                  type: object
                phase:
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
